### ISSUE TITLE
Why onBlur did not pass value like onChange?

### ISSUE THREAD

**Issue by alex-shatalov** [final-form/react-final-form-listeners#4]
by this example https://codesandbox.io/s/72j0kzqr3j it works great with onChange, but we need to validate also onBlur but there is no value in render props

**Comment by erikras** [comment]
Because `OnBlur` only subscribes to `active`, so it doesn't really have the `value`. It _could_, but then it would be notified on every value change. The only reason `OnChange` passes it is because it, by necessity, has it already. This library is meant to be extremely simple, with each component being only 50 lines including types. It would be pretty easy for you to implement your own `OnBlur` that also kept the value, but I don't think it's needed for the majority of use cases.
